# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4e8d83b012fc650d832c94cbdf6c0157d0db8c3f2e8c24fa7399abc8ef3aa2814513a3b0bf324d952d8b4aaecee308364e335ece3a554f30c9b32ecd22835fe

test:
  secret_key_base: 8e3f7d05613c3ddda3b45c257360d3bf20faaca65f6e482b394812096dd229e4b97d4c9043a94e3aba7d55dcc9a4b1216678a2b7d740e549a8d6b37f3cfde355

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
